### ISSUE TITLE
[Linux] PulseAudio button for dynamic rate control causes segfault

### ISSUE THREAD

**Issue by runefox** [byuu/byuu#2]
When using PulseAudio, dynamic rate control is presumably unavailable (as it was in bsnes and higan), however, the toggle is still available. When activated, it may either do nothing or cause a segfault. If enabled on startup, it will consistently cause the segfault. The toggle is also enabled for ALSA, although I don't know whether this is intentional or not.
![Screenshot_20200224_215117](https://user-images.githubusercontent.com/1351044/75218791-f43ea300-574f-11ea-8110-c58345f2480c.png)

**Comment by byuu** [comment]
@RedDwarf69 any chance you could lend a hand with this one please? ^-^;
From https://github.com/byuu/bsnes/pull/287

**Comment by RedDwarf69** [comment]
> When using PulseAudio, dynamic rate control is presumably unavailable (as it was in bsnes and higan), however, the toggle is still available. When activated, it may either do nothing or cause a segfault. If enabled on startup, it will consistently cause the segfault. The toggle is also enabled for ALSA, although I don't know whether this is intentional or not.

DRC is now available with both ALSA and PulseAudio. When selecting ALSA you are likely to get better results if you use https://linux.die.net/man/1/pasuspender.

I can't reproduce your issue. I have just tried with every combination I can think of of the other options and it has always worked. So we are going to need to debug this with your system. Can you provide as much information as you can about it? e.g. Linux version, does the GPU actually support GPU sync, bsnes version, did you build it? with what flags, etc.

**Comment by byuu** [comment]
In that case, it'll help to build with make clean && make build=debug, then grab a gdb stacktrace from there. Don't have to spend more time on this if you don't want to, of course ^-^;

**Comment by runefox** [comment]
I'm using the pkgbuild from the AUR and I realized after posting this that there might be a problem there instead of here. Did a build from scratch using the build=debug and the same thing happens with and without GPU Sync enabled: SIGSEGV (Address boundary error). I'm not sure if/where the debug log should be outputting to. Here's the systemd-coredump line:

Feb 27 08:46:17 systemd-coredump[4968]: Process 4664 (byuu) of user 1000 dumped core.

Stack trace of thread 4664:
#0  0x00005650ee72b510 _ZN4ruby5Audio6outputEPKd (byuu)
#1  0x00005650eead938b _ZN7Program5audioEN4nall14shared_pointerIN5higan4Core6StreamEEE (byuu)
#2  0x00005650ee756f9b _ZN5higan4Core6Stream5writeEPKd (byuu)
#3  0x00005650ee7e6d7b _ZN5higan4Core6Stream6sampleIJddEEEvDpOT_ (byuu)
#4  0x00005650ee7e6de3 _ZN5higan12SuperFamicom3DSP6echo27Ev (byuu)
#5  0x00005650ee7e7262 _ZN5higan12SuperFamicom3DSP4mainEv (byuu)
#6  0x00005650ee7eb660 _ZNK4nall8functionIFvvEE6memberIN5higan12SuperFamicom3DSPEEclEv (byuu)
#7  0x00005650ee7bd951 _ZNK4nall8functionIFvvEEclEv (byuu)
#8  0x00005650ee753e40 n/a (byuu)
-- Subject: Process 4664 (byuu) dumped core
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- Documentation: man:core(5)
--
-- Process 4664 (byuu) crashed and dumped core.

Here's my setup:

OS: Manjaro Linux x86_64
Kernel: 5.5.2-1-MANJARO
Shell: fish 3.0.2
Resolution: 2560x1440, 1440x900
DE: Plasma
CPU: AMD Ryzen 9 3900X 12- (24) @ 3.800GHz
GPU: NVIDIA GeForce RTX 2080 Rev. A (driver version 440.59)
Memory: 7644MiB / 32092MiB

**Comment by Alcaro** [comment]
> _ZN4ruby5Audio6outputEPKd

For anyone without c++filt conveniently available:

ruby::Audio::output(double const*)
Program::audio(nall::shared_pointer\<higan::Core::Stream>)
higan::Core::Stream::write(double const*)
void higan::Core::Stream::sample\<double, double>(double&&, double&&)
higan::SuperFamicom::DSP::echo27()
higan::SuperFamicom::DSP::main()
nall::function\<void ()>::member\<higan::SuperFamicom::DSP>::operator()() const
nall::function\<void ()>::operator()() const

**Comment by RedDwarf69** [comment]
I know nothing about Arch/Manjaro. But https://aur.archlinux.org/packages/bsnes/ says it uses https://download.byuu.org/bsnes_v114-source.zip and DRC was only added in v114.5 (https://github.com/byuu/bsnes/commit/d2211d881812e3ab08c2fc953b1dfecd05bb96e6).

**Comment by byuu** [comment]
Please perhaps try v1.4 and see if it still crashes? I added a check that should stop reaching Audio::output when drivers fail to initialize. You won't get sound of course, but that beats a crash I would think ...

**Comment by runefox** [comment]
The AUR version was just updated to 1.4, but it looks like it's still segfaulting (I did confirm I'm running 1.4):

`Process 32421 (byuu) of user 1000 dumped core.

Stack trace of thread 32421:
#0  0x00005588980bfb04 _ZN4ruby5Audio6outputEPKd (byuu)
#1  0x0000558898466c23 _ZN7Program5audioEN4nall14shared_pointerIN5higan4Core6StreamEEE (byuu)
#2  0x00005588980ef1fe _ZN5higan4Core6Stream5writeEPKd (byuu)
#3  0x00005588981805a9 _ZN5higan12SuperFamicom3DSP6echo27Ev (byuu)
#4  0x0000558897fb1e94 _ZN5higan12SuperFamicom3DSP4mainEv (byuu)
#5  0x0000558898153e7a _ZN5higan12SuperFamicom6Thread5EnterEv (byuu)
#6  0x00005588980eb2a0 n/a (byuu)
#7  0x00007fc7c989c1e0 main_arena (libc.so.6)`

I'm compiling from a fresh git clone now. ... And same thing with that:

`Process 4503 (byuu) of user 1000 dumped core.

Stack trace of thread 4503:
#0  0x000055a0e10a6510 _ZN4ruby5Audio6outputEPKd (byuu)
#1  0x000055a0e145967d _ZN7Program5audioEN4nall14shared_pointerIN5higan4Core6StreamEEE (byuu)
#2  0x000055a0e10d2107 _ZN5higan4Core6Stream5writeEPKd (byuu)
#3  0x000055a0e116332b _ZN5higan4Core6Stream6sampleIJddEEEvDpOT_ (byuu)
#4  0x000055a0e116337f _ZN5higan12SuperFamicom3DSP6echo27Ev (byuu)
#5  0x000055a0e11637fe _ZN5higan12SuperFamicom3DSP4mainEv (byuu)
#6  0x000055a0e1167ed4 _ZNK4nall8functionIFvvEE6memberIN5higan12SuperFamicom3DSPEEclEv (byuu)
#7  0x000055a0e1139779 _ZNK4nall8functionIFvvEEclEv (byuu)
#8  0x000055a0e10cefa0 n/a (byuu)
#9  0x00007f662f8841f0 main_arena (libc.so.6)`

**Comment by RedDwarf69** [comment]
So I didn't understand what v1.4 you were talking about... until I noticed this is not the bsnes emulator, it's byuu!!

So I tried to build v1.4, but it doesn't really build with the Fedora 31 gcc 9.2.1:

```
In file included from sfc/ppu/ppu.cpp:13:
sfc/ppu/mode7.cpp: In lambda function:
sfc/ppu/mode7.cpp:27:78: error: expected ‘:’ before ‘;’ token
   27 |   auto clip = [](int n) -> int { return n & 0x2000 ? (n | ~1023) | (n & 1023); };
      |                                                                              ^
      |                                                                              :
sfc/ppu/mode7.cpp:27:78: error: expected primary-expression before ‘;’ token
```

So I decided to try 93b56add35b6db782e11b0762b53d08d59c041b5 ...but it crashes because of some GUI thing (`#40 0x000000000057eaf1 in hiro::pApplication::processEvents() () at ../hiro/core/../gtk/application.cpp:47`, but it's not the latest version so who cares).

**Comment by byuu** [comment]
Very strange. I know I can patch it in ruby::Audio::output(), but we shouldn't be reading that crash point with a null resampler. We should try to find the root cause of that. The ruby::Video:: functions don't check for ready(), so neither should the ruby::Audio:: functions.

**Comment by runefox** [comment]
Confirming this is still a thing on v2.

**Comment by byuu** [comment]
Yeah, I need someone on Linux to help track down why the resampler is null in Audio::output. Without that, I can't fix it, sorry.
